//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using TN_academic.Areas.Admin.Models;
    using TN_academic.ViewModels;

    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.BlogComments = new HashSet<BlogComment>();
        }

        public Blog(BlogModelForCreate blog)
        {
            this.BlogID = blog.BlogID;
            this.BlogName = blog.BlogName;
            this.Username = blog.Username;
            this.CategoryID = blog.CategoryID;
            this.Content = blog.Content;
            this.Thumbnail = blog.Thumbnail;
            this.CreatedDate = blog.CreatedDate;
            this.Status = blog.Status;
            this.ShortDescription = blog.ShortDescription;
        }

        public Blog(BlogModelForEdit blog)
        {
            this.BlogID = blog.BlogID;
            this.BlogName = blog.BlogName;
            this.Username = blog.Username;
            this.CategoryID = blog.CategoryID;
            this.Content = blog.Content;
            this.Thumbnail = blog.Thumbnail;
            this.CreatedDate = blog.CreatedDate;
            this.Status = blog.Status;
            this.ShortDescription = blog.ShortDescription;
        }

        public Blog(ClientBlogModel blog)
        {
            this.BlogID = blog.BlogID;
            this.BlogName = blog.BlogName;
            this.Username = blog.Username;
            this.CategoryID = blog.CategoryID;
            this.Content = blog.Content;
            this.Thumbnail = blog.Thumbnail;
            this.CreatedDate = blog.CreatedDate;
            this.Status = blog.Status;
            this.ShortDescription = blog.ShortDescription;
        }

        public Blog(ClientBlogModelForEdit blog)
        {
            this.BlogID = blog.BlogID;
            this.BlogName = blog.BlogName;
            this.Username = blog.Username;
            this.CategoryID = blog.CategoryID;
            this.Content = blog.Content;
            this.Thumbnail = blog.Thumbnail;
            this.CreatedDate = blog.CreatedDate;
            this.Status = blog.Status;
            this.ShortDescription = blog.ShortDescription;
        }

        public int BlogID { get; set; }

        [DisplayName("Blog Name")]
        public string BlogName { get; set; }
        public string Username { get; set; }

        [DisplayName("Category")]
        public Nullable<int> CategoryID { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }

        [DisplayName("Created Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ShortDescription { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual User User { get; set; }
    }
}
