//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using TN_academic.Areas.Admin.Models;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Courses = new HashSet<Cours>();
        }

        public Category(CategoryModelForCreate category)
        {
            this.CategoryID = category.CategoryID;
            this.CategoryName = category.CategoryName;
            this.Description = category.Description;
            this.Thumbnail = category.Thumbnail;
        }

        public Category(CategoryModelForEdit category)
        {
            this.CategoryID = category.CategoryID;
            this.CategoryName = category.CategoryName;
            this.Description = category.Description;
            this.Thumbnail = category.Thumbnail;
        }

        [DisplayName("Category ID")]
        public int CategoryID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid category name!")]
        [StringLength(maximumLength: 150, MinimumLength = 5, ErrorMessage = "The category name must be between 5 and 150 characters long.")]
        [DisplayName("Category Name")]
        public string CategoryName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid description!")]
        public string Description { get; set; }
        public string Thumbnail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
