//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using TN_academic.Areas.Admin.Models;
    using TN_academic.CustomValidation;

    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.ExaminationContents = new HashSet<ExaminationContent>();
            this.ExamResults = new HashSet<ExamResult>();
        }

        public Examination(ExaminationModelForCreate exam)
        {
            this.ExamID = exam.ExamID;
            this.ExamName = exam.ExamName;
            this.CourseID = exam.CourseID;
            this.Time = exam.Time;
            this.ExaminationDate = exam.ExaminationDate;
            this.Status = exam.Status;
        }

        [DisplayName("Exam ID")]
        public int ExamID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid exam name!")]
        [StringLength(maximumLength: 255, MinimumLength = 5, ErrorMessage = "The exam name must be between 5 and 255 characters long.")]
        [DisplayName("Exam name")]
        public string ExamName { get; set; }

        public Nullable<int> CourseID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid time")]
        [Range(maximum: Int64.MaxValue, minimum: 0, ErrorMessage = "Time must be a number")]
        public Nullable<int> Time { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}")]
        public Nullable<System.DateTime> ExaminationDate { get; set; }

        public Nullable<int> Status { get; set; }
    
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationContent> ExaminationContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamResult> ExamResults { get; set; }

        
    }
}
