//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResult
    {
        public int ResultID { get; set; }
        public string Username { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public string Result { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Examination Examination { get; set; }
        public virtual User User { get; set; }
    }
}
