//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ExaminationContent
    {
        [DisplayName("Exam ID")]
        public int ExamID { get; set; }

        [DisplayName("Question ID")]
        public int QuestionID { get; set; }

        public Nullable<decimal> Mark { get; set; }
    
        public virtual Examination Examination { get; set; }
        public virtual Question Question { get; set; }
    }
}
