//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class QuestionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionType()
        {
            this.Questions = new HashSet<Question>();
        }

        [DisplayName("Type ID")]
        public int TypeID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid type name!")]
        [StringLength(maximumLength: 150, MinimumLength = 5, ErrorMessage = "The type name must be between 5 and 150 characters long.")]
        [DisplayName("Type Name")]
        public string TypeName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid description!")]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}
