//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using TN_academic.Areas.Admin.Models;
    using TN_academic.ViewModels;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.ExaminationContents = new HashSet<ExaminationContent>();
        }

        public Question(NormalQuestion question)
        {
            this.QuestionID = question.QuestionID;
            this.CourseID = question.CourseID;
            this.TypeID = question.TypeID;
            this.Description = question.Description;
            this.Content = question.Content;
            this.ChoiceA = question.ChoiceA;
            this.ChoiceB = question.ChoiceB;
            this.ChoiceC = question.ChoiceC;
            this.ChoiceD = question.ChoiceD;
            this.Answer = question.Answer;
            this.Level = question.Level;
        }

        public Question(ImageQuestionModelForCreate question)
        {
            this.QuestionID = question.QuestionID;
            this.CourseID = question.CourseID;
            this.TypeID = question.TypeID;
            this.Description = question.Description;
            this.Content = question.Content;
            this.ChoiceA = question.ChoiceA;
            this.ChoiceB = question.ChoiceB;
            this.ChoiceC = question.ChoiceC;
            this.ChoiceD = question.ChoiceD;
            this.Answer = question.Answer;
            this.Level = question.Level;
        }

        public Question(ImageQuestionModelForEdit question)
        {
            this.QuestionID = question.QuestionID;
            this.CourseID = question.CourseID;
            this.TypeID = question.TypeID;
            this.Description = question.Description;
            this.Content = question.Content;
            this.ChoiceA = question.ChoiceA;
            this.ChoiceB = question.ChoiceB;
            this.ChoiceC = question.ChoiceC;
            this.ChoiceD = question.ChoiceD;
            this.Answer = question.Answer;
            this.Level = question.Level;
        }

        public Question(ListeningQuestionModelForCreate question)
        {
            this.QuestionID = question.QuestionID;
            this.CourseID = question.CourseID;
            this.TypeID = question.TypeID;
            this.Description = question.Description;
            this.Content = question.Content;
            this.ChoiceA = question.ChoiceA;
            this.ChoiceB = question.ChoiceB;
            this.ChoiceC = question.ChoiceC;
            this.ChoiceD = question.ChoiceD;
            this.Answer = question.Answer;
            this.Level = question.Level;
        }

        public Question(ListeningQuestionModelForEdit question)
        {
            this.QuestionID = question.QuestionID;
            this.CourseID = question.CourseID;
            this.TypeID = question.TypeID;
            this.Description = question.Description;
            this.Content = question.Content;
            this.ChoiceA = question.ChoiceA;
            this.ChoiceB = question.ChoiceB;
            this.ChoiceC = question.ChoiceC;
            this.ChoiceD = question.ChoiceD;
            this.Answer = question.Answer;
            this.Level = question.Level;
        }



        [DisplayName("ID")]
        public int QuestionID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> CourseID { get; set; }

        public string Description { get; set; }

        public string Content { get; set; }

        public string ChoiceA { get; set; }

        public string ChoiceB { get; set; }

        public string ChoiceC { get; set; }

        public string ChoiceD { get; set; }

        public string Answer { get; set; }

        public Nullable<int> Level { get; set; }

        public HttpPostedFileBase MediaFile { get; set; }

        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationContent> ExaminationContents { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
