//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_academic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserStatu()
        {
            this.Users = new HashSet<User>();
        }

        [DisplayName("Status ID")]
        public int StatusID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid status name!")]
        [StringLength(maximumLength: 100, MinimumLength = 5, ErrorMessage = "The status name must be between 5 and 100 characters long.")]
        [DisplayName("State")]
        public string StatusName { get; set; }
        public Nullable<bool> IsBlock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
